import type { AlumniMember } from './types';

export const alumniData: AlumniMember[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    company: 'Google',
    position: 'Senior Software Engineer',
    graduationYear: 2018,
    department: 'Computer Engineering',
    location: 'Mountain View, CA',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    linkedIn: 'https://linkedin.com/in/priya-sharma',
    email: 'priya@example.com',
    bio: 'Passionate about building scalable systems and mentoring the next generation of engineers.',
    achievements: ['Tech Lead for Google Search', 'Published 15+ research papers', 'Mentor at Women in Tech'],
    skills: ['Python', 'Go', 'Distributed Systems', 'Machine Learning']
  },
  {
    id: '2',
    name: 'Rahul Mehta',
    company: 'Microsoft',
    position: 'Principal Engineer',
    graduationYear: 2017,
    department: 'Information Technology',
    location: 'Seattle, WA',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    linkedIn: 'https://linkedin.com/in/rahul-mehta',
    bio: 'Leading cloud infrastructure initiatives and driving digital transformation.',
    achievements: ['Azure Architecture Expert', 'Microsoft MVP', 'Speaker at 20+ conferences'],
    skills: ['Azure', 'Kubernetes', 'DevOps', 'Cloud Architecture']
  },
  {
    id: '3',
    name: 'Anita Desai',
    company: 'Apple',
    position: 'iOS Lead Developer',
    graduationYear: 2019,
    department: 'Computer Engineering',
    location: 'Cupertino, CA',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    bio: 'Creating beautiful and intuitive mobile experiences for millions of users.',
    achievements: ['Led iOS 16 Camera features', 'Apple Design Award winner', 'Patent holder'],
    skills: ['Swift', 'iOS Development', 'UI/UX Design', 'Core ML']
  },
  {
    id: '4',
    name: 'Vikram Singh',
    company: 'Amazon',
    position: 'Solutions Architect',
    graduationYear: 2016,
    department: 'Electronics Engineering',
    location: 'Austin, TX',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    isActive: false,
    bio: 'Helping enterprises migrate to cloud and optimize their infrastructure.',
    achievements: ['AWS Certified Solutions Architect', 'Led 50+ cloud migrations', 'Tech blogger'],
    skills: ['AWS', 'Terraform', 'Docker', 'System Design']
  },
  {
    id: '5',
    name: 'Kavya Patel',
    company: 'NVIDIA',
    position: 'AI Research Scientist',
    graduationYear: 2020,
    department: 'Computer Engineering',
    location: 'Santa Clara, CA',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    bio: 'Advancing the frontiers of artificial intelligence and deep learning.',
    achievements: ['Published in NeurIPS', 'NVIDIA Research Award', 'PhD in AI'],
    skills: ['PyTorch', 'CUDA', 'Computer Vision', 'Deep Learning']
  },
  {
    id: '6',
    name: 'Arjun Kumar',
    company: 'Meta',
    position: 'Product Manager',
    graduationYear: 2018,
    department: 'Information Technology',
    location: 'Menlo Park, CA',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    bio: 'Building products that connect billions of people around the world.',
    achievements: ['Led WhatsApp Business launch', 'Product of the Year award', 'MBA from Stanford'],
    skills: ['Product Strategy', 'Data Analysis', 'User Research', 'Growth Hacking']
  },
  {
    id: '7',
    name: 'Sneha Reddy',
    company: 'Tesla',
    position: 'Autopilot Engineer',
    graduationYear: 2019,
    department: 'Electronics Engineering',
    location: 'Palo Alto, CA',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    bio: 'Working on the future of autonomous driving and sustainable transportation.',
    achievements: ['Full Self-Driving team lead', 'Autonomous vehicle patents', 'Tesla Innovation Award'],
    skills: ['Computer Vision', 'Robotics', 'C++', 'Neural Networks']
  },
  {
    id: '8',
    name: 'Rohan Gupta',
    company: 'Netflix',
    position: 'Data Scientist',
    graduationYear: 2017,
    department: 'Computer Engineering',
    location: 'Los Gatos, CA',
    avatar: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=150&h=150&fit=crop&crop=face',
    isActive: false,
    bio: 'Using data science to personalize entertainment for 200+ million subscribers.',
    achievements: ['Recommendation algorithm lead', 'Netflix Tech Blog author', 'Data Science conference speaker'],
    skills: ['Python', 'Machine Learning', 'Big Data', 'Statistics']
  },
  {
    id: '9',
    name: 'Meera Joshi',
    company: 'Spotify',
    position: 'Backend Engineer',
    graduationYear: 2020,
    department: 'Information Technology',
    location: 'Stockholm, Sweden',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    isActive: true,
    bio: 'Building scalable music streaming infrastructure for global audiences.',
    achievements: ['Spotify Wrapped backend lead', 'Open source contributor', 'Tech diversity advocate'],
    skills: ['Java', 'Kafka', 'Microservices', 'Distributed Systems']
  }
];