import type { AlumniMember } from './types';

export const alumniData: AlumniMember[] = [
  {
    id: 'a1',
    name: 'Aditi Mehta',
    avatar: 'https://i.pravatar.cc/128?u=aditi',
    isActive: true,
    position: 'Software Engineer',
    company: 'Google',
    department: 'Computer Engineering',
    graduationYear: 2022,
    location: 'Mumbai, India',
    email: 'aditi@alumni.com',
    linkedIn: 'https://linkedin.com/in/aditimehta',
    bio: 'Passionate about scalable systems and AI.',
    achievements: ['Published 2 IEEE papers', 'Hackathon Winner @IITB'],
    skills: ['React', 'Node.js', 'ML']
  },
  {
    id: 'a2',
    name: 'Rahul Singh',
    avatar: 'https://i.pravatar.cc/128?u=rahul',
    isActive: false,
    position: 'Data Analyst',
    company: 'Amazon',
    department: 'Information Technology',
    graduationYear: 2021,
    location: 'Bangalore, India',
    email: 'rahul@alumni.com',
    linkedIn: 'https://linkedin.com/in/rahulsingh',
    bio: 'Data storyteller turning numbers into decisions.',
    achievements: ['Top 10 in Kaggle India', 'Speaker at DataConf 2023'],
    skills: ['Python', 'SQL', 'Tableau']
  },
  {
    id: 'a3',
    name: 'Sneha Kulkarni',
    avatar: 'https://i.pravatar.cc/128?u=sneha',
    isActive: true,
    position: 'UX Designer',
    company: 'Microsoft',
    department: 'Electronics',
    graduationYear: 2020,
    location: 'Pune, India',
    email: 'sneha@alumni.com',
    linkedIn: 'https://linkedin.com/in/snehakulkarni',
    bio: 'Designing intuitive interfaces for a better tomorrow.',
    achievements: ['Designed MS Whiteboard 2.0 UI', 'Led Figma workshops'],
    skills: ['Figma', 'Sketch', 'User Research']
  },
  {
    id: 'a4',
    name: 'Karan Patel',
    avatar: 'https://i.pravatar.cc/128?u=karan',
    isActive: false,
    position: 'Embedded Systems Engineer',
    company: 'Bosch',
    department: 'EXTC',
    graduationYear: 2019,
    location: 'Nashik, India',
    email: 'karan@alumni.com',
    linkedIn: 'https://linkedin.com/in/karanpatel',
    bio: 'Embedded C enthusiast and IoT system architect.',
    achievements: ['Built smart traffic controller', 'Filed 2 patents'],
    skills: ['C', 'STM32', 'IoT']
  },
  {
    id: 'a5',
    name: 'Meera Iyer',
    avatar: 'https://i.pravatar.cc/128?u=meera',
    isActive: true,
    position: 'AI Research Intern',
    company: 'TCS Research',
    department: 'Computer Engineering',
    graduationYear: 2023,
    location: 'Chennai, India',
    email: 'meera@alumni.com',
    linkedIn: 'https://linkedin.com/in/meera-iyer',
    bio: 'Researching multi-modal AI and human-in-the-loop systems.',
    achievements: ['Best paper award @CVPR workshop'],
    skills: ['PyTorch', 'Transformers', 'AI Ethics']
  },
  {
    id: 'a6',
    name: 'Rohan Gupta',
    avatar: 'https://i.pravatar.cc/128?u=rohan',
    isActive: false,
    position: 'Cloud Engineer',
    company: 'Infosys',
    department: 'IT',
    graduationYear: 2022,
    location: 'Delhi, India',
    email: 'rohan@alumni.com',
    linkedIn: 'https://linkedin.com/in/rohang',
    bio: 'Cloud-native infrastructure builder and CI/CD wizard.',
    achievements: ['Created infra for a 10M+ user app'],
    skills: ['AWS', 'Terraform', 'Docker']
  },
  {
    id: 'a7',
    name: 'Neha Sharma',
    avatar: 'https://i.pravatar.cc/128?u=neha',
    isActive: true,
    position: 'Full-Stack Developer',
    company: 'Flipkart',
    department: 'Computer Engineering',
    graduationYear: 2021,
    location: 'Hyderabad, India',
    email: 'neha@alumni.com',
    linkedIn: 'https://linkedin.com/in/nehasharma',
    bio: 'Building scalable e-commerce systems with delightful UX.',
    achievements: ['Revamped Flipkart checkout flow', 'Built internal CMS'],
    skills: ['React', 'Next.js', 'MongoDB']
  },
  {
    id: 'a8',
    name: 'Ankit Desai',
    avatar: 'https://i.pravatar.cc/128?u=ankit',
    isActive: true,
    position: 'ML Engineer',
    company: 'Jio',
    department: 'EXTC',
    graduationYear: 2020,
    location: 'Ahmedabad, India',
    email: 'ankit@alumni.com',
    linkedIn: 'https://linkedin.com/in/ankitdesai',
    bio: 'Working at the intersection of signal processing and ML.',
    achievements: ['Developed speech classifier model', 'Winner @AI4Bharat'],
    skills: ['TensorFlow', 'Signal Processing', 'Edge AI']
  },
  {
    id: 'a9',
    name: 'Divya Nair',
    avatar: 'https://i.pravatar.cc/128?u=divya',
    isActive: false,
    position: 'Tech Consultant',
    company: 'Accenture',
    department: 'IT',
    graduationYear: 2018,
    location: 'Kerala, India',
    email: 'divya@alumni.com',
    linkedIn: 'https://linkedin.com/in/divyanair',
    bio: 'Helping clients transform digitally with cloud-first mindset.',
    achievements: ['Onboarded 5 Fortune 500 clients'],
    skills: ['Business Analysis', 'Cloud Strategy', 'Scrum']
  }
];